### ISSUE TITLE
报错：0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by Huang1932539** [CCYellowStar/zhenxun_plugin_pica#1]
配置都可以，为了以防万一我还上了梯子，但一搜索就报错：
<img width="1277" alt="屏幕截图 2023-02-11 004101" src="https://user-images.githubusercontent.com/122792813/218146952-6c852ab5-44c7-414d-8f6b-d04a2d118f1d.png">
### 请问如何解决？

**Comment by CCYellowStar** [comment]
好像是转换繁体的时候报错了，你搜的是什么

**Comment by Huang1932539** [comment]
> 好像是转换繁体的时候报错了，你搜的是什么
搜pica 东方
搜的这个

**Comment by CCYellowStar** [comment]
我好像没问题，你试试不搜中文呢

**Comment by Huang1932539** [comment]
> 我好像没问题，你试试不搜中文呢

换了animals，但还是一样的报错

**Comment by CCYellowStar** [comment]
我查了是内存释放的问题，你重启试试

**Comment by Huang1932539** [comment]
> 我查了是内存释放的问题，你重启试试

我重启了真寻，但还是有一样的问题

**Comment by CCYellowStar** [comment]
你这个截图红色划线部分是不是中文

**Comment by Huang1932539** [comment]
> 你这个截图红色划线部分是不是中文

嗯是

**Comment by CCYellowStar** [comment]
我查到了，这个繁体转换模块安装路径不能有中文

**Comment by CCYellowStar** [comment]
要不我搞个分支不要繁体转换插件，直接用简体应该也行

**Comment by Huang1932539** [comment]
> 我查到了，这个繁体转换模块安装路径不能有中文

啊这，这是我用户名

**Comment by Huang1932539** [comment]
> 要不我搞个分支不要繁体转换插件，直接用简体应该也行

如果可以的话那太好啦

**Comment by Huang1932539** [comment]
所以，把用户名改成英文就好了?

**Comment by CCYellowStar** [comment]
是这样，但用户名这个好像不好改，要不你试试

**Comment by Huang1932539** [comment]
行，说什么今晚上我也得看上本子

**Comment by CCYellowStar** [comment]
我在发布里已经传了个没有opencc的版本，但我不确定会不会对搜索结果影响

**Comment by Huang1932539** [comment]
> 是这样，但用户名这个好像不好改，要不你试试

这下麻烦了，他提示我用户不对，注销再看看，但没用

**Comment by Huang1932539** [comment]
> 我在发布里已经传了个没有opencc的版本，但我不确定会不会对搜索结果影响

好的，我看看

**Comment by CCYellowStar** [comment]
这个改起来确实麻烦，直接用我传的另一个版本吧

**Comment by Huang1932539** [comment]
> 这个改起来确实麻烦，直接用我传的另一个版本吧

可算改回来了

**Comment by Huang1932539** [comment]
现在行了，他一直说登录失败，是不是网络的问题啊

**Comment by CCYellowStar** [comment]
是的，跟你的代理质量也有关系，你真寻的配置里应该写代理了吧

**Comment by Huang1932539** [comment]
> 寻的配置里应该写代理了吧

啊这，我把这个忘了（主要是不会写）

**Comment by CCYellowStar** [comment]
就是真寻的config.py文件里全局代理，要写你代理的地址加端口

**Comment by Huang1932539** [comment]
<img width="1280" alt="屏幕截图 2023-02-11 020320" src="https://user-images.githubusercontent.com/122792813/218163902-a088dc7c-dedf-45e9-933f-9d8f31b0f662.png">
这个吗？这个是写VPN的吗？

**Comment by Huang1932539** [comment]
我对这方面不是很懂

**Comment by CCYellowStar** [comment]
你代理软件是用的什么

**Comment by Huang1932539** [comment]
> 你代理软件是用的什么

Clash（大概？）

**Comment by Huang1932539** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/122792813/218164406-d4c94bc0-d1b5-48ec-8be3-a30bd9fb438f.png">
这个

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/218164710-a9d4cd76-df7f-440a-a698-43239dd6c7fa.png)

**Comment by Huang1932539** [comment]
一样就可以吗？

**Comment by CCYellowStar** [comment]
把允许局域网接人打开

**Comment by Huang1932539** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/122792813/218165806-7cbd2b7c-f670-4598-b4d4-de34c22a5e5e.png">
打开了，这回报这个错误。原本后面没有无法连接的这串英文

**Comment by CCYellowStar** [comment]
多试几次，这个api就是不稳定

**Comment by Huang1932539** [comment]
所以现在就是api的问题，本地问题都解决了是吧

**Comment by CCYellowStar** [comment]
对，一般登录是多试几次能登录上的，然后其他查询什么的就看脸了

**Comment by Huang1932539** [comment]
好的，那今晚上麻烦了。有什么别的问题我再反馈

**Comment by CCYellowStar** [comment]
一般出现开始下载或者开始整理之类的字样就是基本成功了，等他下完就行
