### ISSUE TITLE
搜pika命令中转发的聊天记录存在一点问题

### ISSUE THREAD

**Issue by 318256996** [CCYellowStar/zhenxun_plugin_pica#5]
命令窗无任何报错，
搜pika命令，转发的聊天记录一个字符一个字符发送，后面使用看pika命令不太方便，手动安装和插件仓库安装都试过了，都存在这个问题
![image](https://user-images.githubusercontent.com/85478653/229542134-18346605-e61e-4112-837b-6bc9d9d59f1d.png)
能否修改成随机本子一样，直接发送出信息：
![image](https://user-images.githubusercontent.com/85478653/229542631-83def95f-9689-40c1-b50f-8a2cbaf3120e.png)

**Comment by CCYellowStar** [comment]
原因是如果只搜出一个结果的时候他也会被当成多个消息进行for循环然后就变成逐字发送

**Comment by CCYellowStar** [comment]
现在修了，你重下一下

**Comment by 318256996** [comment]
> 现在修了，你重下一下

谢谢大佬，已经能正常使用了
